"""职位过滤配置 - 定义不同职位的项目和工作经历过滤规则"""

ROLE_FILTERS = {
    "data_development": {
        "name": "数据开发",
        "include_projects": [
            {"field": "data_domain", "pattern": ".*数据.*|.*BI.*"},
            {"field": "ai_component_flag", "value": True},
        ],
        "exclude_projects": [
            {"field": "project_name", "exact": "Move To HP Cloud"},
            {"field": "data_domain", "pattern": ".*基础设施.*"},
        ],
        "sort_by": "relevance_then_time",
        "persona": {
            "label": "数据平台负责人视角",
            "instructions": {
                "zh": "以数据平台/湖仓负责人的身份撰写，突出数据可靠性、治理指标、性能优化与跨区域复制价值。",
                "en": "Write as a data platform lead, highlighting reliability, governance KPIs, performance tuning, and multi-region rollout value."
            },
        },
        "field_visibility": {
            "governance_artifacts": True,
            "decision_accountability": True,
            "responsibility_focus": True,
            "impact_metrics": True,
            "management_scope": True,
            "role_perspective": True,
            "project_overview": True,
            "challenges_or_objectives": True,
            "responsibilities": True,
            "architecture_or_solution": True,
            "deliverables_or_features": True,
            "metrics_or_impact": True,
            "tech_stack": True,
            "tools_platforms": True,
            "data_domain": True,
            "ai_component_flag": True,
            "process_or_methodology": True,
            "team_info": True,
            "notes": True,
            "timeframe": True,
            "company_or_context": True,
            "role_title": True,
        },
    },
    "full_stack": {
        "name": "全栈开发",
        "include_projects": [
            {"field": "responsibility_focus", "contains": ["implementation", "architecture"]},
        ],
        "exclude_projects": [
            {"field": "data_domain", "pattern": ".*爬虫.*"},
        ],
        "sort_by": "relevance_then_time",
        "persona": {
            "label": "全栈产品工程视角",
            "instructions": {
                "zh": "以全栈工程师身份强调端到端交付、前后端协同、上线速度与可维护性。",
                "en": "Write as a full-stack engineer, stressing end-to-end delivery, frontend-backend trade-offs, release velocity, and maintainability."
            },
        },
        "field_visibility": {
            "responsibility_focus": True,
            "impact_metrics": True,
            "management_scope": True,
            "role_perspective": True,
            "project_overview": True,
            "challenges_or_objectives": True,
            "responsibilities": True,
            "architecture_or_solution": True,
            "deliverables_or_features": True,
            "metrics_or_impact": True,
            "tech_stack": True,
            "tools_platforms": True,
            "process_or_methodology": True,
            "team_info": True,
            "notes": True,
            "timeframe": True,
            "company_or_context": True,
            "role_title": True,
            "governance_artifacts": False,
            "decision_accountability": False,
            "data_domain": False,
            "ai_component_flag": False,
        },
    },
    "ai_development": {
        "name": "AI应用开发",
        "include_projects": [
            {"field": "ai_component_flag", "value": True},
        ],
        "exclude_projects": [],
        "sort_by": "relevance_then_time",
        "persona": {
            "label": "AI 应用工程视角",
            "instructions": {
                "zh": "以 AI 工程负责人身份描述建模、推理性能、PromptOps 与成本治理等实现细节。",
                "en": "Write as an AI application engineer, highlighting model design, inference performance, prompt operations, and cost governance details."
            },
        },
        "field_visibility": {
            "ai_component_flag": True,
            "impact_metrics": True,
            "management_scope": True,
            "role_perspective": True,
            "project_overview": True,
            "challenges_or_objectives": True,
            "responsibilities": True,
            "architecture_or_solution": True,
            "deliverables_or_features": True,
            "metrics_or_impact": True,
            "tech_stack": True,
            "tools_platforms": True,
            "process_or_methodology": True,
            "team_info": True,
            "notes": True,
            "timeframe": True,
            "company_or_context": True,
            "role_title": True,
            "governance_artifacts": True,
            "decision_accountability": False,
            "responsibility_focus": False,
            "data_domain": False,
        },
    },
    "project_manager": {
        "name": "项目经理 / Project Manager",
        "include_projects": [
            {"field": "responsibility_focus", "contains": ["planning", "stakeholder_management", "compliance"]},
            {"field": "decision_accountability", "contains": ["delivery_owner", "risk_governance"]},
            {"field": "role_title", "pattern": ".*(项目经理|Project Manager).*"},
        ],
        "exclude_projects": [
            {"field": "role_title", "pattern": ".*(测试|运维).*"},
        ],
        "sort_by": "relevance_then_time",
        "persona": {
            "label": "项目交付与技术决策视角",
            "instructions": {
                "zh": "以项目交付负责人/技术项目经理的身份撰写，强调范围/进度/成本控制、跨团队协作、风险与变更治理，以及对关键技术决策的评估与把关。",
                "en": "Write as a project delivery owner or technical project manager, emphasizing scope/schedule/budget control, cross-team delivery, risk and change governance, and evaluation of major technical decisions.",
            },
        },
        "field_visibility": {
            # 强制展示项目管理/治理相关字段
            "management_scope": True,
            "decision_accountability": True,
            "governance_artifacts": True,
            "impact_metrics": True,
            "role_perspective": True,
            "project_overview": True,
            "challenges_or_objectives": True,
            "responsibilities": True,
            "timeframe": True,
            "company_or_context": True,
            "role_title": True,
            # 保留精简的技术上下文，支撑决策与风险表述
            "architecture_or_solution": True,
            "tech_stack": True,
            "tools_platforms": True,
            # 对项目经理视角噪声较大的实现细节可以隐藏
            "deliverables_or_features": True,
            "metrics_or_impact": True,
            "team_info": True,
            "notes": True,
            "process_or_methodology": False,
            "ai_component_flag": False,
            "responsibility_focus": False,
            "data_domain": False,
        },
    },
    "product_manager": {
        "name": "Generative AI 产品经理",
        "include_projects": [
            {"field": "responsibility_focus", "contains": ["commercialization", "stakeholder_management"]},
            {"field": "decision_accountability", "contains": ["commercial_strategy", "risk_governance"]},
            {"field": "role_title", "pattern": ".*产品.*|.*Product.*"},
        ],
        "exclude_projects": [
            {"field": "role_title", "pattern": ".*(测试|运维).*"},
        ],
        "sort_by": "relevance_then_time",
        "persona": {
            "label": "AI 产品设计/策略视角",
            "instructions": {
                "zh": "以 AI 产品设计师或产品经理的身份撰写，强调用户洞察、商业化假设、干系人对齐与实验节奏，把技术亮点转译为产品价值。",
                "en": "Write as an AI product designer/PM, emphasizing user insights, monetization hypotheses, stakeholder alignment, and experiment cadence while translating technical depth into product value."
            },
        },
        "field_visibility": {
            "decision_accountability": True,
            "responsibility_focus": True,
            "impact_metrics": True,
            "management_scope": True,
            "role_perspective": True,
            "project_overview": True,
            "challenges_or_objectives": True,
            "responsibilities": True,
            "deliverables_or_features": True,
            "metrics_or_impact": True,
            "team_info": True,
            "notes": True,
            "timeframe": True,
            "company_or_context": True,
            "role_title": True,
            "governance_artifacts": True,
            "architecture_or_solution": False,
            "tech_stack": False,
            "tools_platforms": False,
            "process_or_methodology": False,
            "ai_component_flag": False,
            "data_domain": False,
        },
    },
    "ai_product_designer": {
        "name": "AI 产品设计师",
        "include_projects": [],
        "exclude_projects": [],
        "sort_by": "relevance_then_time",
        "persona": {
            "label": "AI 产品体验视角",
            "instructions": {
                "zh": "以 AI 产品设计师身份，从用户旅程、体验策略、变现模型、设计系统等角度讲述项目，并明确设计决策如何驱动指标。",
                "en": "Write as an AI product designer, focusing on user journeys, experience strategy, monetization models, and design systems, explaining how each design decision drives key metrics."
            },
        },
        "field_visibility": {
            "impact_metrics": True,
            "management_scope": True,
            "role_perspective": True,
            "project_overview": True,
            "challenges_or_objectives": True,
            "responsibilities": True,
            "deliverables_or_features": True,
            "metrics_or_impact": True,
            "team_info": True,
            "notes": True,
            "timeframe": True,
            "company_or_context": True,
            "role_title": True,
            "decision_accountability": False,
            "responsibility_focus": False,
            "governance_artifacts": False,
            "architecture_or_solution": False,
            "tech_stack": False,
            "tools_platforms": False,
            "process_or_methodology": False,
            "ai_component_flag": False,
            "data_domain": False,
        },
    },
    "ai_engineer": {
        "name": "AI 开发工程师",
        "include_projects": [],
        "exclude_projects": [],
        "sort_by": "relevance_then_time",
        "persona": {
            "label": "AI 开发工程视角",
            "instructions": {
                "zh": "以 AI 开发工程师/技术负责人的身份撰写，深入描述架构演进、模型/推理优化、灰度与监控手段，突出可扩展性与稳定性。",
                "en": "Write as an AI engineer or tech lead, diving into architecture evolution, model/inference optimizations, rollout safety, and observability to highlight scalability and stability."
            },
        },
        "field_visibility": {
            "ai_component_flag": True,
            "impact_metrics": True,
            "management_scope": True,
            "role_perspective": True,
            "project_overview": True,
            "challenges_or_objectives": True,
            "responsibilities": True,
            "architecture_or_solution": True,
            "deliverables_or_features": True,
            "metrics_or_impact": True,
            "tech_stack": True,
            "tools_platforms": True,
            "process_or_methodology": True,
            "team_info": True,
            "notes": True,
            "timeframe": True,
            "company_or_context": True,
            "role_title": True,
            "governance_artifacts": True,
            "decision_accountability": False,
            "responsibility_focus": False,
            "data_domain": False,
        },
    },
}
